import "./globals.css";
import { Toaster } from "@/components/ui/toaster"
import { Manrope as FontSans } from "next/font/google";
import ScrollObserver from "@/lib/ScrollObserver";
import {cn} from "@/lib/utils";
import Navbar from "@/components/Navbar";
// import Navbar from "@/components/Navbar";
export const metadata = {
  title: "Melodio world of songs",
  description: "Generated by Javapuffs",
};
export const dynamic = 'force-dynamic';

const fontSans = FontSans({
    subsets: ["latin"],
    variable: "--font-sans",
    display: "swap",
});
export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cn(
          "min-h-screen bg-gray-1100 font-sans bg-[url('/grid-2.svg')]  text-slate-900 antialiased dark:bg-slate-900 dark:text-slate-50 transition-all duration-500 ",
          fontSans.variable
      )}>

        <Navbar/>
        <main className="flex min-h-screen  items-center bg-gray-1100 text-stone-50">

          <ScrollObserver>{children}</ScrollObserver>
          <Toaster />
        </main>
      </body>
    </html>
  );
}
