import "./globals.css";

export const metadata = {
  title: "User Management",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <main className="flex min-h-screen  items-center bg-gray-900 text-stone-50">
          {children}
        </main>
      </body>
    </html>
  );
}
