import React from "react";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import { Manrope as FontSans, Inconsolata } from "next/font/google";
import ScrollObserver from "@/lib/ScrollObserver";
import { cn } from "@/lib/utils";
import { Session, createClientComponentClient, createServerComponentClient } from '@supabase/auth-helpers-nextjs';
import Navbar from "@/components/nav/Navbar";
import { cookies } from "next/headers";
import { Database } from "@/types/supabase";

export const metadata = {
    title: "Melodio world of songs",
    description: "Generated by Javapuffs",
};

export const dynamic = 'force-dynamic';

const fontSans = FontSans({
    subsets: ["latin"],
    variable: "--font-sans",
    display: "swap",
});

const incosolata = Inconsolata({
    subsets: ["latin"],
    variable: "--font-ins",
    display: "swap",
});

export default async function RootLayout({ children }: { children: React.ReactNode; }) {
    const supabase = createServerComponentClient<Database>({ cookies });

    const {
        data: { session },
    } = await supabase.auth.getSession();

    return (
        <html lang="en">
        <body className={cn(
            "h-screen bg-gray-1100 font-sans  no-scrollbar text-slate-100 antialiased dark:bg-slate-900 dark:text-slate-50 transition-all duration-500 ",
            fontSans.variable, incosolata.variable
        )}>
        <Navbar session={session} />
        <main className="bg-gray-1100 dark:bg-black">
            <ScrollObserver>{children}</ScrollObserver>
            <Toaster />
        </main>
        </body>
        </html>
    );
}
